"""Initial migrations.

Revision ID: e6ce7804d987
Revises: 
Create Date: 2024-08-16 06:11:53.290689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ce7804d987'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalation_policy',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('team_id', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('team_id', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident')
    op.drop_table('service')
    op.drop_table('escalation_policy')
    op.drop_table('team')
    # ### end Alembic commands ###
